version: '3'

networks:
  app-tier:
    driver: bridge
  graylog:
    driver: bridge

services:
  buildpython:
    build:
      context: ./BuildPython/
      dockerfile: Dockerfile


  rabbit1:
      image: "rabbitmq:3-management"
      hostname: "rabbit1"
      environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
        RABBITMQ_DEFAULT_VHOST: "/"
      ports:
        - "15672:15672" #This port exposes the web interface. 
        - "5672:5672"
      networks:
        - app-tier
      restart: on-failure

  sciflask:
    build:
      context: ./SciFlask
      dockerfile: Dockerfile
    networks:
      - app-tier 
      - graylog
    logging:
      driver: "json-file"
#      options: 
#        syslog-address: "tcp://:5044"
#        syslog-facility: "daemon"
#    ports: #this was for the first iteration with flask. 

  send_data:
    build:
      context: ./SendData
      dockerfile: Dockerfile
    networks:
      - app-tier 
    
  elk:
    image: sebp/elk
    environment:
      - ES_CONNECT_RETRY=60
    networks:
      - graylog
      - app-tier
    ports:
      - 5601:5601
      - 9200:9200
      - 9300:9300
      - 5044:5044


  filebeat:
    image: bargenson/filebeat
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    environment: 
      - LOGSTASH_HOST="localhost"
      - LOGSTASH_PORT=5044
      - SHIPPER_NAME=filebeat
    networks:
      - graylog
      - app-tier